import React, { Component } from "react";

import data from "./data.json";
import slider, { Range } from "rc-slider";
import "rc-slider/assets/index.css";

export default class Table extends Component {
  state = {
    rangeValues: [1970, 2018],
  };
  handleChange = (value) => {
    console.log(value);
    this.setState({
      rangeValues: value,
    });
  };
  render() {
    return (
      <div className="container">
        <h3>S&P 500 Total Returns</h3>
        <p>
          The total returns of the S&P 500 index are listed by year. Total returns include two components: the return
          generated by dividends and the return generated by price changes in the index. While most individuals focus
          only on the price returns of the index, dividends play an important factor in overall investment returns.
        </p>
        <Range onAfterChange={this.handleChange} defaultValue={this.state.rangeValues} min={1970} max={2018} />
        <br></br>
        <br></br>
        <h5>S&P 500 Total Returns by Year</h5>
        <div className>
          <table className="table table-hover">
            <thead>
              <tr>
                <th>Year</th>
                <th>Total Return</th>
                <th>Cumulative returns</th>
              </tr>
            </thead>
            <tbody>
              {data
                .filter((row) => {
                  if (row.year < this.state.rangeValues[0]) {
                    return false;
                  }
                  if (row.year > this.state.rangeValues[1]) {
                    return false;
                  }

                  return true;
                })
                .sort((a, b) => a.year - b.year)
                .map((row, i) => (
                  <tr key={i}>
                    <td>{row.year}</td>
                    <td>{row.totalReturn}</td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  }
}
